"""Affiliate Center (affiliate-id.tokopedia.com) API: endpoints, bodies and answers as the
pages send and read them. Every function takes a ShopApi -- the calling application's handle
on one shop's signed session."""
from typing import Any, Dict, Optional, Protocol


class ShopApi(Protocol):
    """One shop's session, as the application provides it (see tiktok_shop.client)."""

    def common_query(self, is_seller: bool = False) -> Dict[str, str]: ...
    def headers(self, referer: Optional[str] = None) -> Dict[str, str]: ...
    def signed(self, method: str, url: str, query: Any, body: Any = None,
               headers: Optional[Dict[str, str]] = None, sign_body: bool = True) -> bytes: ...
    def send(self, method: str, url: str, data: Any, headers: Optional[Dict[str, str]] = None) -> bytes: ...
    @property
    def seller_id(self) -> Optional[str]: ...
    @property
    def region(self) -> str: ...
